
version: 2

models:
    - name: menu_model
      description: "Snowflake menu table"
      columns:
          - name: menu_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
